/**
 * Operacoes que ainda NAO declaram schema de resposta -- a divida herdada.
 *
 * ESTA LISTA SO PODE ENCOLHER. O teste que a consome falha de duas maneiras:
 * rota NOVA sem schema (a divida cresceu) e rota da lista que ganhou schema
 * sem sair daqui (a lista mentiu). Sem a segunda checagem a allowlist viraria
 * documentacao que envelhece -- exatamente o que o snapshot OpenAPI existe
 * para impedir.
 *
 * POR QUE NAO ADOTAR AS 113 DE UMA VEZ (FIX #163): declarar resposta em ~40
 * controllers e uma fatia inteira, e diff desse tamanho se revisa mal. O
 * criterio escolhido -- exigir so das rotas NOVAS -- esta escrito aqui para
 * nao virar divida silenciosa, que era a ressalva da propria issue.
 *
 * COMO SAIR DA LISTA: declare o schema no controller (`@ApiOkResponse`,
 * `@ApiCreatedResponse`, ...), regenere o snapshot com
 * `ATUALIZAR_OPENAPI=1 pnpm --filter @arenahub/api test:integration` e apague
 * a linha correspondente daqui.
 */
export const OPERACOES_SEM_SCHEMA_DE_RESPOSTA: readonly string[] = [
  'DELETE /api/v1/students/{id}/health-context/{factor}',
  'DELETE /api/v1/students/{studentId}/biometric-identities/{identityId}',
  'GET /api/v1/access-events',
  'GET /api/v1/access-events/{id}',
  'GET /api/v1/assessment-imports/pending',
  'GET /api/v1/assessment-imports/sessions/{sessionId}',
  'GET /api/v1/assessment-imports/{id}',
  'GET /api/v1/assessment-imports/{id}/file-url',
  'GET /api/v1/assessments/{id}',
  'GET /api/v1/auth/me',
  'GET /api/v1/billing/delinquency',
  'GET /api/v1/consent-documents/biometric/current',
  'GET /api/v1/device-sync-jobs',
  'GET /api/v1/devices',
  'GET /api/v1/devices/{id}',
  'GET /api/v1/edge/commands',
  'GET /api/v1/exports/{id}',
  'GET /api/v1/invoices',
  'GET /api/v1/invoices/{id}',
  'GET /api/v1/operations/alerts',
  'GET /api/v1/operations/overview',
  'GET /api/v1/payment-attempts/{id}',
  'GET /api/v1/payments/{id}/status',
  'GET /api/v1/plans',
  'GET /api/v1/plans/{id}',
  'GET /api/v1/receipts/{id}',
  'GET /api/v1/reconciliation/items',
  'GET /api/v1/students',
  'GET /api/v1/students/{id}',
  'GET /api/v1/students/{id}/ai-analyses/consent',
  'GET /api/v1/students/{id}/ai-analyses/latest',
  'GET /api/v1/students/{id}/assessments',
  'GET /api/v1/students/{id}/attendance',
  'GET /api/v1/students/{id}/biometric-consent',
  'GET /api/v1/students/{id}/body-evolution',
  'GET /api/v1/students/{id}/entitlements',
  'GET /api/v1/students/{id}/health-context',
  'GET /api/v1/students/{id}/health-goals',
  'GET /api/v1/students/{id}/health-goals/progress',
  'GET /api/v1/students/{id}/health-progress',
  'GET /api/v1/students/{id}/timeline',
  'GET /api/v1/students/{studentId}/assessment-sessions',
  'GET /api/v1/students/{studentId}/biometric-identities',
  'GET /api/v1/units',
  'GET /api/v1/units/{id}',
  'GET /api/v1/users',
  'GET /health/live',
  'GET /health/ready',
  'GET /version',
  'PATCH /api/v1/assessments/{id}/draft',
  'PATCH /api/v1/devices/{id}',
  'PATCH /api/v1/students/{id}',
  'PATCH /api/v1/students/{id}/status',
  'PATCH /api/v1/units/{id}',
  'POST /api/v1/access-events/exports',
  'POST /api/v1/access/manual-overrides',
  'POST /api/v1/assessment-imports/sessions/{sessionId}/confirm',
  'POST /api/v1/assessment-imports/{id}/confirm',
  'POST /api/v1/assessment-imports/{id}/discard',
  'POST /api/v1/assessment-imports/{id}/fields/{fieldId}',
  'POST /api/v1/assessments/{id}/corrections',
  'POST /api/v1/assessments/{id}/publish',
  'POST /api/v1/auth/login',
  'POST /api/v1/auth/logout',
  'POST /api/v1/auth/mfa/confirm',
  'POST /api/v1/auth/mfa/setup',
  'POST /api/v1/auth/refresh',
  'POST /api/v1/billing/delinquency/apply',
  'POST /api/v1/billing/financial-overrides',
  'POST /api/v1/billing/financial-overrides/{id}/revoke',
  'POST /api/v1/consent-documents/biometric',
  'POST /api/v1/devices',
  'POST /api/v1/edge/access-decisions',
  'POST /api/v1/edge/access-events/{id}/passage',
  'POST /api/v1/edge/commands/{id}/lease',
  'POST /api/v1/edge/heartbeat',
  'POST /api/v1/edge/sync-results/batch',
  'POST /api/v1/entitlements/courtesy',
  'POST /api/v1/exports/{id}/cancel',
  'POST /api/v1/exports/{id}/download',
  'POST /api/v1/health-goals/{id}/close',
  'POST /api/v1/invoices',
  'POST /api/v1/invoices/{id}/manual-payment',
  'POST /api/v1/invoices/{id}/payments/card',
  'POST /api/v1/invoices/{id}/payments/card-checkout',
  'POST /api/v1/invoices/{id}/payments/pix',
  'POST /api/v1/operations/alerts/{id}/acknowledge',
  'POST /api/v1/payment-methods',
  'POST /api/v1/payments/{id}/receipt',
  'POST /api/v1/payments/{id}/refunds',
  'POST /api/v1/plans',
  'POST /api/v1/plans/{id}/prices',
  'POST /api/v1/reconciliation/items/{id}/resolve',
  'POST /api/v1/reconciliation/runs',
  'POST /api/v1/refunds/{id}/observe',
  'POST /api/v1/students',
  'POST /api/v1/students/{id}/ai-analyses',
  'POST /api/v1/students/{id}/assessment-imports',
  'POST /api/v1/students/{id}/assessments',
  'POST /api/v1/students/{id}/biometric-consent',
  'POST /api/v1/students/{id}/health-context',
  'POST /api/v1/students/{id}/health-exports',
  'POST /api/v1/students/{id}/health-goals',
  'POST /api/v1/students/{studentId}/biometric-identities',
  'POST /api/v1/students/{studentId}/biometric-identities/upload',
  'POST /api/v1/subscriptions',
  'POST /api/v1/subscriptions/{id}/actions',
  'POST /api/v1/subscriptions/{id}/recurrence/cancel',
  'POST /api/v1/units',
  'POST /api/v1/users/invitations',
  'POST /api/v1/users/invitations/accept',
  'POST /api/v1/webhooks/payments/{provider}',
];
